### ISSUE TITLE
S3Path confusion

### ISSUE THREAD

**Issue by ericphanson** [JuliaCloud/AWSS3.jl#125]
Is there a way to download a zip file from an S3Path?

I tried
```julia
s3_path = S3Path("s3://mybucket/myfile.zip")
isfile(s3_path) # true
bytes = read(s3_path) # ERROR: MethodError: no method matching Array{UInt8,1}(::OrderedCollections.LittleDict{Union{String, Symbol},Any,Array{Union{String, Symbol},1},Array{Any,1}})
```
and
```julia
cp(s3_path, p"local_dir/file.zip") # ERROR: MethodError: no method matching Array{UInt8,1}(::OrderedCollections.LittleDict{Union{String, Symbol},Any,Array{Union{String, Symbol},1},Array{Any,1}})
```
and
```julia
open(s3_path, "r") do io
      read(io)
end # ERROR: MethodError: no method matching Array{UInt8,1}(::OrderedCollections.LittleDict{Union{String, Symbol},Any,Array{Union{String, Symbol},1},Array{Any,1}})
```
I think these are all from https://github.com/JuliaCloud/AWS.jl/issues/224. (It really seems to me that raw bytes should always be returned). Am I missing a trick, or does one need to use the low-level api to do this?

**Comment by ericphanson** [comment]
Not sure if this one is related or not:
```julia
julia> dir = AWSS3.S3Path("s3://mybucket/mydir/")
p"s3://mybucket/mydir/"

julia> readdir(dir)
ERROR: TaskFailedException:
KeyError: key "IsTruncated" not found
Stacktrace:
 [1] getindex(::OrderedCollections.LittleDict{Union{String, Symbol},Any,Array{Union{String, Symbol},1},Array{Any,1}}, ::String) at ./abstractdict.jl:492
 [2] macro expansion at /home/ec2-user/.julia/packages/AWSS3/eJYxO/src/AWSS3.jl:453 [inlined]
 [3] macro expansion at /home/ec2-user/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [4] (::AWSS3.var"#37#38"{String,Int64,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},AWS.AWSConfig,SubString{String},String})(::Channel{Any}) at /home/ec2-user/.julia/packages/AWSS3/eJYxO/src/AWSS3.jl:432
 [5] (::Base.var"#485#486"{AWSS3.var"#37#38"{String,Int64,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},AWS.AWSConfig,SubString{String},String},Channel{Any}})() at ./channels.jl:129
Stacktrace:
 [1] try_yieldto(::typeof(Base.ensure_rescheduled)) at ./task.jl:656
 [2] wait at ./task.jl:713 [inlined]
 [3] wait(::Base.GenericCondition{ReentrantLock}) at ./condition.jl:106
 [4] take_unbuffered(::Channel{Any}) at ./channels.jl:405
 [5] take! at ./channels.jl:381 [inlined]
 [6] iterate(::Channel{Any}, ::Nothing) at ./channels.jl:448
 [7] iterate at ./channels.jl:447 [inlined]
 [8] isdir(::AWSS3.S3Path) at /home/ec2-user/.julia/packages/AWSS3/eJYxO/src/s3path.jl:182
 [9] readdir(::AWSS3.S3Path) at /home/ec2-user/.julia/packages/AWSS3/eJYxO/src/s3path.jl:326
 [10] top-level scope at REPL[30]:1
```

**Comment by ericphanson** [comment]
I wonder if it's a configuration error on my end?

**Comment by mattBrzezinski** [comment]
> Is there a way to download a zip file from an S3Path?
> 
> I tried
> 
> ```julia
> s3_path = S3Path("s3://mybucket/myfile.zip")
> isfile(s3_path) # true
> bytes = read(s3_path) # ERROR: MethodError: no method matching Array{UInt8,1}(::OrderedCollections.LittleDict{Union{String, Symbol},Any,Array{Union{String, Symbol},1},Array{Any,1}})
> ```

Which version of `AWSS3.jl` are you using? I've just tried this on both `v0.6.12` and `v0.8.1` and am successfully able to get the contents of the ZIP.

**Comment by ericphanson** [comment]
Thanks for checking, I'm on v0.8.1. I wonder if it's a configuration issue then

**Comment by ericphanson** [comment]
if I follow the README, I get
```
julia> using AWS

julia> aws = AWS.aws_config()
ERROR: MethodError: objects of type Base.RefValue{AWSConfig} are not callable
Stacktrace:
 [1] top-level scope at REPL[4]:1
```

**Comment by mattBrzezinski** [comment]
> if I follow the README, I get
> 
> ```julia
> julia> using AWS
> 
> julia> aws = AWS.aws_config()
> ERROR: MethodError: objects of type Base.RefValue{AWSConfig} are not callable
> Stacktrace:
>  [1] top-level scope at REPL[4]:1
> ```

Ah... I need to update that documentation. That used to be a `global const`, now it's a `Ref`. The following code will 

From [AWS.jl](https://github.com/JuliaCloud/AWS.jl/blob/23c829eb2564a6edfc1124257388d29c648d5dd5/src/AWS.jl#L32-L66)
```julia
"""
    global_aws_config()
Retrieve the global AWS configuration.
If one is not set, create one with default configuration options.
# Keywords
- `kwargs...`: AWSConfig kwargs to be passed along if the global configuration is not already set
# Returns
- `AWSConfig`: The global AWS configuration
"""
function global_aws_config(; kwargs...)
    if !isassigned(aws_config) || !isempty(kwargs)
        aws_config[] = AWSConfig(; kwargs...)
    end

    return aws_config[]
end


"""
    global_aws_config(config::AWSConfig)
Set the global AWSConfig.
# Arguments
- `config::AWSConfig`: The AWSConfig to set in the global state
# Returns
- `AWSConfig`: Global AWSConfig
"""
function global_aws_config(config::AWSConfig)
    return aws_config[] = config
end
```

**Comment by ericphanson** [comment]
Aha, if I do `AWS.aws_config[] = AWSConfig(; region="us-east-2")` then things start working! I'm running this on an EC2 instance in `us-east-2`,
```julia
shell> ec2-metadata --availability-zone
placement: us-east-2b
```
 so it's a little surprising that `AWSConfig()` gives me `us-east-1`, but maybe that's the source of my woes.

**Comment by mattBrzezinski** [comment]
> Aha, if I do `AWS.aws_config[] = AWSConfig(; region="us-east-2")` then things start working! I'm running this on an EC2 instance in `us-east-2`,

You can also do the following at the beginning of your Julia session/script and the default configuration will have it to the proper region:

```julia
global_aws_config(;region="us-east-2")
```

> so it's a little surprising that `AWSConfig()` gives me `us-east-1`, but maybe that's the source of my woes.

If you set the env var `AWS_DEFAULT_REGION` or pass in the kwarg `region` the credentials will use that, otherwise they default to `us-east-1`.

**Comment by ericphanson** [comment]
Sounds good, thanks for the info and the help!
