### ISSUE TITLE
Backport `isdir` fix to 0.6

### ISSUE THREAD

**Issue by arnaudh** [JuliaCloud/AWSS3.jl#131]
The 0.7.2 patch release fixed a bug in `isdir` https://github.com/JuliaCloud/AWSS3.jl/pull/96 (the bug shows up on Julia 1.5: calling `isdir` on an existing S3 folder seems to always return false).

A few packages at Invenia still depend on the 0.6 major release, and updating to 0.8 is non-trivial work due to moving from AWSCore and onto AWS, therefore we should backport the fix to 0.6.

**Comment by omus** [comment]
I'm assuming this is no longer relevant
