### ISSUE TITLE
Walkpath is slow, we can make it easily 10x faster.

### ISSUE THREAD

**Issue by oxinabox** [JuliaCloud/AWSS3.jl#158]
Related to #147 

Copying this over from some internal code @rofinn  wrote, so that this doesn't get lost and forgotten entirely.

> Slight optimization over the default `readdir(::S3Path)` based method to avoid multiple
calls when we want to grab all prefixes at once and we don't care about order:
> we may need tests or custom logic to ensure that ordering is consistent.

```julia
function _walkpath(fp::S3Path)
    # Select objects within that prefix
    objects = s3_list_objects(fp.config, fp.bucket, fp.key; delimiter="")

    # Extract keys from the results and strip the prefix out
    keys = [lstrip(replace(o["Key"], fp.key => ""), '/') for o in objects]

    # Filter any empty keys (e.g, prefix)
    filter!(!isempty, keys)

    # Return the keys joined with the original prefix
    return joinpath.(fp, keys)
end
```

Benchmark

```julia
julia> using FilePathsBase, AWSS3, BenchmarkTools

julia> fp = S3Path("REDACTED");

julia> @btime collect(walkpath($fp));
  465.464 ms (10916 allocations: 635.63 KiB)

julia> @btime collect(_walkpath($fp));
  66.557 ms (2430 allocations: 131.33 KiB)
```

**Comment by ericphanson** [comment]
Just to say

> `replace(o["Key"], fp.key => "")`

is the correctness bug I fixed in #164; probably want `chop` like in https://github.com/JuliaCloud/AWSS3.jl/pull/164/files#diff-31b593db3c82f33730f4af58846ed59213199a8dd973bddc4f70f1e1721d6719R346.
