### ISSUE TITLE
S3Paths: get config at use-time, not construction time?

### ISSUE THREAD

**Issue by ericphanson** [JuliaCloud/AWSS3.jl#168]
If you create an S3Path, by default it calls `global_aws_config()` to set the config. I can see why it does that, but I think a better default would be to set the config to `nothing`, and then we can replace calls to `fp.config` by something like `@something(fp.config, global_aws_config())` (that could even be a `getproperty` overload).

What is the difference? If you use S3Paths as hardcoded constants like
```julia
module MyPkg
const DATASET_PATH = S3Path("s3://...")

...
end
```
then you need s3 access at precompile time (and `using` time) otherwise the `global_aws_config()` command will throw. Also, if you do
```julia
module MyPkg
const DATASET_PATH = S3Path("s3://...")

function __init__()
    global_aws_config(; my_settings...)
end
...
end
```
then in fact `DATASET_PATH` will be constructed *before* `__init__` is called, so you will get the wrong config settings (i.e. the default ones, not the ones you set in `__init__`). (This gave @ararslan a tricky error the other day).

I think in general it's kind of a "gotcha", because users usually think of paths as a simple stringy-object-that-points-at-a-resource, not something stateful. For example, if I construct a path, realize my config is wrong, fix my global config, then I need to construct the path again-- but new users might not realize that and confused/frustrated as to why it still doesn't work.

Note: this would only apply to the default construction; if you pass a config at construction time then that config would be used always (since `fp.config` would not be nothing, it would be a config).

#### If we need to always fetch the config when using a path, would it be slow?

I don't think so:
```julia
julia> function f()
       config = global_aws_config()
       return config.region # do something with the config
       end
f (generic function with 1 method)

julia> @benchmark f()
BechmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  17.062 ns … 33.830 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     17.092 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   17.168 ns ±  0.832 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▃▄▇██▇▆▅▃▂▂▁   ▁▃▃▁▁                                      ▂
  ▃▇██████████████████████▆▇▇█▇▅▆▇▆▆▆▆▆▇▆▅▆▅▅▅▄▄▅▃▁▅▃▃▄▁▃▁▃▄▄ █
  17.1 ns      Histogram: log(frequency) by time      17.3 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

17-30 ns is not bad at all, so I think it's negligible.

#### Would this change be breaking?

Maybe; it changes the default behavior from capturing the config at construction time to using the latest `global_aws_config` at using time. However, I would be kind of surprised if anyone was relying on this, e.g. setting the global config, creating the path, then changing the global config, and counting on the path using the old one. But even if it was breaking, I think it's a worthwhile change.

**Comment by femtomc** [comment]
Yes to this.

**Comment by omus** [comment]
I suspect the original reason `S3Path` came to encapsulate the configuration was mainly for convenience so that the standard file system functions could just take a single argument. As an `S3Path` can be accessed via many different configurations I think it doesn't really make sense to tie it to any specific configuration.

To that end I think it may be sensible to remove the `config` field from `S3Path`. Doing that however may require us to think of alternative approaches to execute functions under alternate `AWSConfig` without having to always modify the global one (maybe a do-block)?.

**Comment by ericphanson** [comment]
I think the config is sometimes useful! I use it extensively in the tests of https://github.com/JuliaLogging/TensorBoardLogger.jl/pull/103 because I don't want to mutate global AWS config from tests.

**Comment by rofinn** [comment]
Yeah, removing the `config` field removes the entire benefit of this type and the filepaths API cause then you'd need to know what type it is at the call site.

**Comment by omus** [comment]
> Yeah, removing the `config` field removes the entire benefit of this type and the filepaths API cause then you'd need to know what type it is at the call site... to know that you need to pass a config through.

This just means it's infeasible to use the `config` keyword to overwrite the configuration. We could however remove the `config` field from `S3Path` and get access to it much like is done in #175. If you want to temporarily set an `AWSConfig` you could do something like this:
```julia
p = S3Path(...)  # no config included here

aws_config(...) do  # Set an AWSConfig within the context of the do-block
    stat(p)
end
```
This should allow temporarily setting the configuration while avoiding having to have `config` included in `S3Path` which allows for it to dynamically pick up the configuration like this. Is there any use case I'm not considering?

**Comment by ericphanson** [comment]
> Is there any use case I'm not considering?

This is kinda theoretical, but if we were using Minio and s3 within the same workflow, we could do `my_minio_path = S3Path(...; config=my_minio_config)` and `my_s3_path = S3Path(...; config=my_aws_config)`. Or you could have paths to two separate AWS regions this way. I've never done either of those though and the do-block form would capture the uses I've had.

**Comment by ararslan** [comment]
FWIW another point I came across that speaks in favor of this change: If you have the `AWS_PROFILE` environment variable set to something, precompile a module with top-level `S3Path` constants, exit Julia, restart with a different `AWS_PROFILE` set, load the module, and access the constants, they've held onto (and thus retain the permissions of!!!) the previous profile.
