### ISSUE TITLE
total size of all objects within a "directory"

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaCloud/AWSS3.jl#210]
Dumb question, do we really not have any way to determine the total size of all objects within a "directory"?  I distinctly remember that whatever we did for `stat` does not work because directories in S3 aren't real (and this is the reason `stat` always gives zeros right now).

I'm pretty sure the only way of doing this is listing all files within a "directory" and then adding up the result.

I just wanted to ask around if we somehow did this already before I implement it.

**Comment by ericphanson** [comment]
I believe that's the only way that the upstream s3 API gives to do it. However, there's s3 inventory which I've never used: https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory.html. I believe it's a separate service where they manage some indices for you that you can query.

**Comment by mattBrzezinski** [comment]
You could be able to use prefixes and delimiters when running `S3.list_objects` to get files in a "directory", and then iterate and add up results.

AFAIK there is no functionality that does this through the base AWS API.

**Comment by ExpandingMan** [comment]
Ok [done](https://github.com/JuliaCloud/AWSS3.jl/pull/211), though we may have some API consistency issues (more for FilePathsBase than AWSS3 specifically) to discuss.

**Comment by ericphanson** [comment]
Closed by #211
