### ISSUE TITLE
CI test failure:  MethodError: no method matching parse(::Type{S3Path{Nothing}}, ::S3Path{Nothing})

### ISSUE THREAD

**Issue by morris25** [JuliaCloud/AWSS3.jl#227]
The following error occurs several times in [current CI pipelines](https://github.com/JuliaCloud/AWSS3.jl/runs/4390051615?check_suite_focus=true):
```
MethodError: no method matching parse(::Type{S3Path{Nothing}}, ::S3Path{Nothing})
  Closest candidates are:
    parse(::Type{P}, ::AbstractString; kwargs...) where P<:AbstractPath at ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:77
  Stacktrace:
    [1] _broadcast_getindex_evalf
      @ ./broadcast.jl:670 [inlined]
    [2] _broadcast_getindex
      @ ./broadcast.jl:653 [inlined]
    [3] getindex
      @ ./broadcast.jl:597 [inlined]
    [4] copy
      @ ./broadcast.jl:899 [inlined]
    [5] materialize
      @ ./broadcast.jl:860 [inlined]
    [6] readpath(p::S3Path{Nothing}; join::Bool, sort::Bool)
      @ FilePathsBase ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:713
    [7] readpath
      @ ~/.julia/packages/FilePathsBase/qgXdE/src/path.jl:708 [inlined]
    [8] macro expansion
      @ /opt/hostedtoolcache/julia/1.7.0/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
    [9] macro expansion
      @ ~/work/AWSS3.jl/AWSS3.jl/test/s3path.jl:59 [inlined]
   [10] macro expansion
      @ /opt/hostedtoolcache/julia/1.7.0/x64/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [11] test_s3_readpath(p::PathSet{S3Path{Nothing}})
      @ Main ~/work/AWSS3.jl/AWSS3.jl/test/s3path.jl:57
```
Likely causes are changes in FilePathsBase or the S3 bucket failing to be created/being deleted by another pipeline.  I haven't investigated the error fully but the last successful pipeline was 15 days ago. FilePathsBase was at v0.9.15 on the last successful run. It is now at v0.9.17.

**Comment by rofinn** [comment]
The source of the error is that FilePathsBase still assumes that the output of `readdir` is `Vector{String}` which is documented in the README. When adding support for the `join` and `sort` kwargs I intentionally maintained that distinction to avoid type instabilities in the `readdir` function. AWSS3 has chosen to ignore that and return `Vector{S3Path}` when `join=true`. I don't have a good suggestion for this, but I noted it when I was making the FilePathsBase change. My instinct is that AWSS3 should override `readpath` if it wants to maintain the type instability.

- https://github.com/rofinn/FilePathsBase.jl/pull/152/files#diff-4e2b33a7304f53abf36fe9499936056b993077836e4b72a5c5ae016d8c6d6d1fR713
- https://github.com/JuliaCloud/AWSS3.jl/pull/129#discussion_r752441343

**Comment by omus** [comment]
> The source of the error is that FilePathsBase still assumes that the output of `readdir` is `Vector{String}` which is documented in the README

Can you provide a link to the documentation you are referring to? I assumed it was FilePathsBase.jl's README but there isn't a reference to `readdir` at all.

It seems that the best path forward is to set an upperbound on FilePathsBase here to avoid running into this problem and then make a breaking release that always returns strings like `join=true` intended.

**Comment by ericphanson** [comment]
> always returns strings like `join=true` intended

I'm a broken record at this point, but I don't think there's anything from the Base API to suggest `join=true` should return alwyas return strings, and making this choice will mean that `read(first(readdir(path; join=true)))` will work for Base paths but not S3Paths, limiting S3Paths usage in generic code.

**Comment by rofinn** [comment]
> Can you provide a link to the documentation you are referring to? I assumed it was FilePathsBase.jl's README but there isn't a reference to readdir at all.

https://rofinn.github.io/FilePathsBase.jl/stable/api/#Aliases-1
