### ISSUE TITLE
Allow `S3Path` handle version ID `"null"`

### ISSUE THREAD

**Issue by alexmchan** [JuliaCloud/AWSS3.jl#241]
When S3 versioning is enabled in a bucket, objects that were created in that bucket before versioning was enabled have a version ID of `"null"`. Currently, `S3Path` does not support version ID's that are `"null"` even though this is a valid ID.  For example, doing something like this is valid:

```
>> aws s3api get-object --bucket my-bucket --key my/key.txt --version-id null local/path/key.txt
```

From the [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html):

> Objects that are stored in your bucket before you set the versioning state have a version ID of null. When you enable versioning, existing objects in your bucket do not change. What changes is how Amazon S3 handles the objects in future requests.

**Comment by kleinschmidt** [comment]
Seems simple enough to special case `"null"` in the check for valid versionId strings.

**Comment by omus** [comment]
Did a little bit of experimentation with the AWS S3 API to ensure we fully understand the behaviour.

- Object in an unversioned bucket:
    - `aws s3api head-object --bucket $unversioned --key $object --output json`

        ```json
        {
            "AcceptRanges": "bytes",
            "LastModified": "2022-02-16T19:42:57+00:00",
            "ContentLength": 1024,
            "ETag": "\"a\"",
            "ContentType": "binary/octet-stream",
            "Metadata": {}
        }
        ```

    - `aws s3api list-object-versions --bucket $unversioned --prefix $object --output json`

        ```json
        {
            "Versions": [
                {
                    "ETag": "\"a\"",
                    "Size": 0,
                    "StorageClass": "STANDARD",
                    "Key": "object",
                    "VersionId": "null",
                    "IsLatest": true,
                    "LastModified": "2022-02-16T19:42:57+00:00",
                    "Owner": {
                        "ID": "..."
                    }
                }
            ]
        }
        ```

- Object in a versioned bucket created after versioning is enabled:

    - `aws s3api head-object --bucket $versioned --key $object --output json`
        
        ```json
        {
            "AcceptRanges": "bytes",
            "LastModified": "2021-09-22T13:16:28+00:00",
            "ContentLength": 1024,
            "ETag": "\"b\"",
            "VersionId": "WFQNlL1gbJxi0A84tKvUo5_LnHuZ2rlm",
            "ContentType": "application/octet-stream",
            "ServerSideEncryption": "AES256",
            "Metadata": {}
        }
        ```

    - `aws s3api list-object-versions --bucket $versioned --prefix $object --output json`

        ```json
        {
            "Versions": [
                {
                    "ETag": "\"b\"",
                    "Size": 1024,
                    "StorageClass": "STANDARD",
                    "Key": "object",
                    "VersionId": "WFQNlL1gbJxi0A84tKvUo5_LnHuZ2rlm",
                    "IsLatest": true,
                    "LastModified": "2021-09-22T13:16:28+00:00",
                    "Owner": {
                        "ID": "..."
                    }
                }
            ]
        }
        ```

- Object in a versioned bucket created before versioning is enabled:

    - `aws s3api head-object --bucket $before_versioned --key $object --output json`

        ```json
        {
            "AcceptRanges": "bytes",
            "LastModified": "2020-04-14T23:33:07+00:00",
            "ContentLength": 1024,
            "ETag": "\"c\"",
            "VersionId": "null",
            "ContentType": "application/octet-stream",
            "Metadata": {}
        }
        ```

    - `aws s3api list-object-versions --bucket $before_versioned --prefix $object --output json`

        ```json
        {
            "Versions": [
                {
                    "ETag": "\"c\"",
                    "Size": 1024,
                    "StorageClass": "STANDARD",
                    "Key": "object",
                    "VersionId": "null",
                    "IsLatest": true,
                    "LastModified": "2020-04-14T23:33:07+00:00",
                    "Owner": {
                        "ID": "..."
                    }
                }
            ]
        }
        ```

Here's a more complicated case where a previously unversioned file was updated with a new version:

```json
{
    "Versions": [
        {
            "ETag": "\"d\"",
            "Size": 4,
            "StorageClass": "STANDARD",
            "Key": "demo",
            "VersionId": "uBwuGlhsnM7.zN1ckgQdnKnV5S.4L4dp",
            "IsLatest": true,
            "LastModified": "2022-02-16T20:01:45+00:00",
            "Owner": {
                "ID": "..."
            }
        },
        {
            "ETag": "\"d\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "demo",
            "VersionId": "null",
            "IsLatest": false,
            "LastModified": "2022-02-16T19:42:57+00:00",
            "Owner": {
                "ID": "..."
            }
        }
    ]
}
```

And here is how access works with this versioned object:

- `aws s3api get-object --bucket x --key y --version-id null`: returns the original file
- `aws s3api get-object --bucket x --key y --version-id uBwuGlhsnM7.zN1ckgQdnKnV5S.4L4dp`: returns the specific version the file (happens to be the latest version)
- `aws s3api get-object --bucket x --key y`: returns the latest version the file

From this experiment I theorized that any S3 unversioned object can use "null" as a version ID. This theory was validated by successfully using `aws s3api ... --version-id null` on an object in an bucket without versioning enabled.
