### ISSUE TITLE
`KeyError: key "ETag" not found` in `s3_multipart_upload`

### ISSUE THREAD

**Issue by ericphanson** [JuliaCloud/AWSS3.jl#246]
This is code that has run probably a couple dozen (or hundred?) times since I last touched it, but just now I guess AWS decided to not give an ETag back? No idea what went wrong.
```julia
ERROR: LoadError: KeyError: key "ETag" not found
Stacktrace:
 [1] getindex(h::Dict{SubString{String}, SubString{String}}, key::String)
   @ Base ./dict.jl:481
 [2] s3_upload_part(aws::AWS.AWSConfig, upload::OrderedCollections.LittleDict{Union{String, Symbol}, Any, Vector{Union{String, Symbol}}, Vector{Any}}, part_number::Int64, part_data::Vector{UInt8}; args::Dict{String, Any}, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ AWSS3 ~/.julia/packages/AWSS3/D1gQl/src/AWSS3.jl:841
 [3] s3_upload_part(aws::AWS.AWSConfig, upload::OrderedCollections.LittleDict{Union{String, Symbol}, Any, Vector{Union{String, Symbol}}, Vector{Any}}, part_number::Int64, part_data::Vector{UInt8})
   @ AWSS3 ~/.julia/packages/AWSS3/D1gQl/src/AWSS3.jl:829
 [4] s3_multipart_upload(aws::AWS.AWSConfig, bucket::SubString{String}, path::String, io::IOStream, part_size_mb::Int64; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ AWSS3 ~/.julia/packages/AWSS3/D1gQl/src/AWSS3.jl:884
 [5] s3_multipart_upload (repeats 2 times)
   @ ~/.julia/packages/AWSS3/D1gQl/src/AWSS3.jl:872 [inlined]
```

I guess we should retry if we don't get the ETag? Not really sure what's going on. The docs say if it's successful, it should be a 200 response w/ an ETag. Maybe it wasn't a 200 but we didn't throw in AWS.jl or something?

**Comment by omus** [comment]
Can you reproduce this issue? The [`UploadPart`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html#API_UploadPart_ResponseSyntax) is definitely expected to return an "ETag". We should add some error checking here to ensure that the header is returned or otherwise show the HTTP response.

**Comment by ericphanson** [comment]
It happened at like 2/5 attempts, and then I added a try-catch to keep going (was trying to get something running before end of day).

Possibly related: we updated from AWS.jl v1.60.3 to 1.74.1, and AWSS3 0.9.2 to 0.9.5 earlier today.

**Comment by mattBrzezinski** [comment]
Yeah I don't understand what can be happening here, the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html#API_UploadPart_ResponseSyntax) state that `ETag` will always be returned in the header.

I assume this just happens sporadically? It'd be nice if we could catch the response from AWS and see what's all there.

**Comment by peteristhegreat** [comment]
After digging into this more in our case, we switched our backend to Downloads.jl and it consistently failed on this error.

The solution was to patch s3_upload_part to look at the lowercase version of `ETag` => `etag`, and then it would work.  I'll work on a PR for this.  It would happen whenever there was more than one part with a multipart upload.

**Comment by ericphanson** [comment]
Ooh, good find!

**Comment by ericphanson** [comment]
Maybe https://github.com/JuliaCloud/AWS.jl/issues/547 is related?
