### ISSUE TITLE
AWS version locked to 1.63.1 which limits us to HTTP 0.9? 

### ISSUE THREAD

**Issue by JustinSGray** [JuliaCloud/AWSS3.jl#273]
The latest AWS release supports HTTP V1. 

AWS 1.63.1 only supports HTTP 0.9. 

Is there a hard reason  not to support the latest AWS version to get access to the lattest HTTP?

**Comment by mattBrzezinski** [comment]
We're not? 😄 Just run `] add AWS@1.79` to get the most recent version of it

```julia
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [fbe9abb3] AWS v1.79.0
  [1c724243] AWSS3 v0.10.2
```

**Comment by JustinSGray** [comment]
my appologies. I got confused by the version spec and thought it was locked to a specific instance. I see now that its 1.63.1 and up!

**Comment by mattBrzezinski** [comment]
No worries! To be honest it is a bit confusing at times, the [documentation](https://pkgdocs.julialang.org/v1/compatibility/) is pretty good for clarifying different compat statements.

🚀
