### ISSUE TITLE
Joining `S3Path` with `/` fails to add first directory split 

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaCloud/AWSS3.jl#71]
```julia
julia> Path("foo") / "bar" / "baz"
p"foo/bar/baz"

# expected p"s3://foo/bar/baz"
julia> S3Path("s3://foo") / "bar" / "baz"
p"s3://foobar/baz"  
```

I think this is happening because it's just dispatching to `join`
```julia
julia> @which S3Path("s3://foo") / "bar" / "baz"
/(root::AbstractPath, pieces::Union{AbstractString, AbstractPath}...) in FilePathsBase at /Users/nick/.julia/packages/FilePathsBase/oi7XZ/src/path.jl:215
```
https://github.com/rofinn/FilePathsBase.jl/blob/v0.7.0/src/path.jl#L214-L216

and for `join` we identify S3 "directories" by the trailing `/`
```julia
julia> @which join(S3Path("s3://foo"), "bar", "baz")
join(prefix::S3Path, pieces::AbstractString...) in AWSS3 at /Users/nick/.julia/packages/AWSS3/VMuUL/src/s3path.jl:94
```
https://github.com/JuliaCloud/AWSS3.jl/blob/v0.6.8/src/s3path.jl#L93-L97

As the `S3Path` docstring explains, this is to do with S3 "faking" directories
https://github.com/JuliaCloud/AWSS3.jl/blob/v0.6.8/src/s3path.jl#L18-L23

But while the `join` behaviour is arguably correct (although i think it's arguable)
```julia
julia> join(S3Path("s3://foo"), "bar", "baz")
p"s3://foobar/baz"
```
it leads to surprising behaviour when using the `/` syntax.

I wonder whether is is worth special-casing the `/` syntax for `S3Paths` to behave like
```julia
julia> S3Path("s3://foo") / "bar" / "baz"
p"s3://foo/bar/baz"  
```

**Comment by nickrobinson251** [comment]
tbh I think the `join` behaviour is just incorrect. Unless there's a justification for the first of these not adding a `/` when the second one does?
```julia
julia> join(S3Path("s3://foo"), "baz")
p"s3://foobaz"

julia> join(S3Path("s3://foo/bar"), "baz")
p"s3://foo/bar/baz" 
```

**Comment by nickrobinson251** [comment]
any objections to changing the behaviour here, @rofinn @mattBrzezinski ?

**Comment by rofinn** [comment]
I'm fine with changing it.
