### ISSUE TITLE
JMESPath support for list_objects

### ISSUE THREAD

**Issue by kafisatz** [JuliaCloud/AWSS3.jl#97]
Would it be possible to include support for JMESPath in the future?
See https://blog.scottlowe.org/2019/03/01/advanced-ami-filtering-with-jmespath/  for examples.
This would allow something along (AWS CLI command)
```aws s3api list-objects --bucket somebucket --query "Contents[?contains(Key,'-20200527-')]"```
As that the query in the current implementation is a Dict, thus it does not seem straightforward to me make this work.

**Comment by mattBrzezinski** [comment]
Hi Bernhard,

Looking at the example query above, this seems to filter the results of a bucket to contain the key `-20200527-`. I do not think that this is currently possible to do in either this package or `AWSCore.jl`.

You can use the `prefix` optional argument, however this will only return back objects that begin with the sequence of characters.

```julia
using AWSCore.Services: s3

resp = s3("GET", "/mattbr-test-bucket", Dict("prefix"=>"test"))
resp["Contents"]
```

The Julia interfaces for AWS are built off of [aws-sdk-js](https://github.com/aws/aws-sdk-js/tree/master/apis), it seems that the `--query` feature is not featured in these (at least from my poking around) so it wouldn't be generated.

Currently if you want to do something similar I would recommend just returning all the objects back from your s3 bucket, and performing a second statement to filter them down.

**Comment by kafisatz** [comment]
Thanks for the feedback. Your recommendation certainly works (this is my current approach). I was hoping that a JMESPath query might be faster than the suggested workaround.
